[project]
name = "spacex-pipeline"
version = "0.1.0"
description = "SpaceX Data Pipeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt>=1.5.0",
    "polars>=1.20.0",
    "requests>=2.32.3",
]
