[project]
name = "spacex-pipeline"
version = "0.1.0"
description = "SpaceX Data Pipeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.9.3",
    "dlt[motherduck]>=1.9.0",
    "requests>=2.32.3",
]
