name: Run pipeline
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  load-data:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
    
      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run data load script
        env: 
          DESTINATION__MOTHERDUCK__CREDENTIALS__DATABASE: spacex
          DESTINATION__MOTHERDUCK__CREDENTIALS__PASSWORD: ${{ secrets.DESTINATION__MOTHERDUCK__CREDENTIALS__PASSWORD }}

        run: |
          uv run dlt/spacex_pipeline.py --directory
      
      - name: test directory location
        run: ls 

      - name: Run dbt build
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.DESTINATION__MOTHERDUCK__CREDENTIALS__PASSWORD }}
        run: |
          cd dbt
          dbt build
          cd ..